config/routes.rb
Papertracker::Application.routes.draw do
  resources :document_states

  resources :documents

  resources :document_types

  devise_for :users do
    get '/login' => 'devise/sessions#new', :as => :login
    get '/logout' => 'devise/sessions#destroy', :as => :logout
  end

  root :to => 'dashboards#show'

end

app/models/document_state.rb
class DocumentState < ActiveRecord::Base
  belongs_to :document_state_prev, :class_name => "DocumentState", :foreign_key => "document_state_prev_id"

  attr_accessible :document_state_prev_id, :name

end

app/controllers/document_states_controller.rb
class DocumentStatesController < ApplicationController
  # GET /document_states
  # GET /document_states.json
  def index
    @document_states = DocumentState.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @document_states }
    end
  end

  # GET /document_states/1
  # GET /document_states/1.json
  def show
    @document_state = DocumentState.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @document_state }
    end
  end

  # GET /document_states/new
  # GET /document_states/new.json
  def new
    @document_state = DocumentState.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @document_state }
    end
  end

  # GET /document_states/1/edit
  def edit
    @document_state = DocumentState.find(params[:id])
  end

  # POST /document_states
  # POST /document_states.json
  def create
    @document_state = DocumentState.new(params[:document_state])

    respond_to do |format|
      if @document_state.save
        format.html { redirect_to @document_state, notice: 'Document state was successfully created.' }
        format.json { render json: @document_state, status: :created, location: @document_state }
      else
        format.html { render action: "new" }
        format.json { render json: @document_state.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /document_states/1
  # PUT /document_states/1.json
  def update
    @document_state = DocumentState.find(params[:id])

    respond_to do |format|
      if @document_state.update_attributes(params[:document_state])
        format.html { redirect_to @document_state, notice: 'Document state was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @document_state.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /document_states/1
  # DELETE /document_states/1.json
  def destroy
    @document_state = DocumentState.find(params[:id])
    @document_state.destroy

    respond_to do |format|
      format.html { redirect_to document_states_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/document_states_helper.rb
module DocumentStatesHelper
end

app/views/document_states/_form.html.erb
<%= form_for(@document_state) do |f| %>
  <% if @document_state.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@document_state.errors.count, "error") %> prohibited this document_state from being saved:</h2>

      <ul>
      <% @document_state.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :document_state_prev_id %><br />
    <%= f.select(:document_state_prev_id, DocumentState.all.map{ |c| [c.name, c.id] } ) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/document_states/edit.html.erb
<h1>Editing document_state</h1>

<%= render 'form' %>

<%= link_to 'Show', @document_state %> |
<%= link_to 'Back', document_states_path %>

app/views/document_states/index.html.erb
<h1>Listing document_states</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Document state prev</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @document_states.each do |document_state| %>
  <tr>
    <td><%= document_state.name %></td>
    <td><%= document_state.document_state_prev.try(:name) %></td>

    <td><%= link_to 'Show', document_state %></td>
    <td><%= link_to 'Edit', edit_document_state_path(document_state) %></td>
    <td><%= link_to 'Destroy', document_state, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Document state', new_document_state_path %>

app/views/document_states/new.html.erb
<h1>New document_state</h1>

<%= render 'form' %>

<%= link_to 'Back', document_states_path %>

app/views/document_states/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @document_state.name %>
</p>

<p>
  <b>Document state prev:</b>
  <%= @document_state.document_state_prev.try(:name) %>
</p>


<%= link_to 'Edit', edit_document_state_path(@document_state) %> |
<%= link_to 'Back', document_states_path %>