config/routes.rb
Papertracker::Application.routes.draw do
  resources :document_states

  resources :documents

  resources :document_types

  devise_for :users do
    get '/login' => 'devise/sessions#new', :as => :login
    get '/logout' => 'devise/sessions#destroy', :as => :logout
  end

  root :to => 'dashboards#show'

end

app/controllers/document_types_controller.rb
class DocumentTypesController < ApplicationController
  # GET /document_types
  # GET /document_types.json
  def index
    @document_types = DocumentType.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @document_types }
    end
  end

  # GET /document_types/1
  # GET /document_types/1.json
  def show
    @document_type = DocumentType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @document_type }
    end
  end

  # GET /document_types/new
  # GET /document_types/new.json
  def new
    @document_type = DocumentType.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @document_type }
    end
  end

  # GET /document_types/1/edit
  def edit
    @document_type = DocumentType.find(params[:id])
  end

  # POST /document_types
  # POST /document_types.json
  def create
    @document_type = DocumentType.new(params[:document_type])

    respond_to do |format|
      if @document_type.save
        format.html { redirect_to @document_type, notice: 'Document type was successfully created.' }
        format.json { render json: @document_type, status: :created, location: @document_type }
      else
        format.html { render action: "new" }
        format.json { render json: @document_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /document_types/1
  # PUT /document_types/1.json
  def update
    @document_type = DocumentType.find(params[:id])

    respond_to do |format|
      if @document_type.update_attributes(params[:document_type])
        format.html { redirect_to @document_type, notice: 'Document type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @document_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /document_types/1
  # DELETE /document_types/1.json
  def destroy
    @document_type = DocumentType.find(params[:id])
    @document_type.destroy

    respond_to do |format|
      format.html { redirect_to document_types_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/document_types_helper.rb
module DocumentTypesHelper
end

app/views/document_types/_form.html.erb
<%= form_for(@document_type) do |f| %>
  <% if @document_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@document_type.errors.count, "error") %> prohibited this document_type from being saved:</h2>

      <ul>
      <% @document_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :template %><br />
    <%= f.text_area :template %>
  </div>

  <div class="field">
    <%= f.label :since_date %><br />
    <%= f.text_field :since_date %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/document_types/edit.html.erb
<h1>Editing document_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @document_type %> |
<%= link_to 'Back', document_types_path %>

app/views/document_types/index.html.erb
<h1>Listing document_types</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @document_types.each do |document_type| %>
  <tr>
    <td><%= document_type.name %></td>
    <td><%= link_to 'Show', document_type %></td>
    <td><%= link_to 'Edit', edit_document_type_path(document_type) %></td>
    <td><%= link_to 'Destroy', document_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Document type', new_document_type_path %>

app/views/document_types/new.html.erb
<h1>New document_type</h1>

<%= render 'form' %>

<%= link_to 'Back', document_types_path %>

app/views/document_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @document_type.name %>
</p>


<%= link_to 'Edit', edit_document_type_path(@document_type) %> |
<%= link_to 'Back', document_types_path %>